import { roboto } from "../ui/fonts";
import "../globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params}) {
  const locale = params?.locale;
  return (
    <html lang={locale}>
      <body className={`${roboto.className} antialiased`}>
          {children}
      </body>
    </html>
  );
}
